Repository ansible-collections/ansible.scm, pull requests merged in 2023-03, with the labels that each got.

#62 Add release drafter
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
  changelogs/fragments/62.yaml
Labels: safe to test

#63 Move release drafter config to .github
  .github/release-drafter.yml
  changelogs/fragments/63.yaml
Labels: safe to test

#64 Add environment details to push
  .github/workflows/push.yml
  changelogs/fragments/64.yaml
Labels: safe to test, skip-changelog

#67 Bring release drafter config here
  .github/release-drafter.yml
Labels: skip-changelog

#69 Fix version name in GHA
  .github/release-drafter.yml
  .github/workflows/push.yml
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  galaxy.yml
Labels: bug

#70 Fix string replacment
  .config/dictionary.txt
  .github/workflows/push.yml
Labels: bug, safe to test

#71 Fix v replacement
  .github/workflows/push.yml
Labels: bug, safe to test

#73 Enable branch protection rules
  .github/workflows/push.yml
  changelogs/changelog.yaml
Labels: bug, safe to test

#76 Remove extra changelog entries
  .github/workflows/push.yml
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: safe to test, skip-changelog

#75 Rename git_away to git_publish
  .flake8
  README.md
  docs/ansible.scm.git_here_module.rst
  docs/ansible.scm.git_publish_module.rst
  plugins/action/git_publish.py
  plugins/modules/git_here.py
  plugins/modules/git_publish.py
  tests/integration/targets/success/tasks/main.yaml
  tests/unit/test_smoke.py
Labels: safe to test, major

#79 Cleanup push and galaxy file
  .github/workflows/push.yml
  galaxy.yml
Labels: safe to test, skip-changelog

#80 Update the galaxy.yml file during the push event
  .github/workflows/push.yml
Labels: safe to test, skip-changelog, Impatience allowed

#81 Create user specified parent directory
  plugins/action/git_here.py
  tests/integration/targets/user_dir/tasks/main.yaml
Labels: bug, safe to test

#84 Changelog updated
  .github/workflows/push.yml
  changelogs/changelog.yaml
Labels: safe to test, skip-changelog, Impatience allowed

#86 Changelog updated
  changelogs/changelog.yaml
Labels: safe to test, skip-changelog

#85 Update to reflect ansible-core 2.12+
  README.md
  meta/runtime.yml
Labels: safe to test, skip-changelog, Impatience allowed

#78 Rename git_here to git_retrieve
  .flake8
  README.md
  docs/ansible.scm.git_publish_module.rst
  docs/ansible.scm.git_retrieve_module.rst
  plugins/action/git_retrieve.py
  plugins/modules/git_publish.py
  plugins/modules/git_retrieve.py
  tests/integration/targets/key_checking/tasks/main.yaml
  tests/integration/targets/success/tasks/main.yaml
  tests/integration/targets/timeout/tasks/main.yaml
  tests/integration/targets/user_dir/tasks/main.yaml
  tests/unit/test_smoke.py
Labels: safe to test, major

#88 Changelog updated
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: safe to test, skip-changelog, Impatience allowed
